# Generated by Django 2.1 on 2018-08-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180828_2353'),
        ('users', '0002_auto_20180828_1511'),
    ]

    operations = [
    ]
